on:
  workflow_dispatch:
  schedule:
    - cron: '39 8 * * *'

concurrency:
  group: main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v5
        with:
          path: .
          # sync/upstream ブランチのハッシュを取るのが理想
          key: sync-cache-${{ github.sha }}
          restore-keys: sync-cache-

      - run: |
          cat > /tmp/key.private << EOL
          ${{ secrets.SYNC_PRIVATE_KEY }}
          EOL
          chmod 600 /tmp/key.private

          if [[ ! -d .git ]]; then
            git init
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git config core.sshCommand "ssh -i /tmp/key.private -F /dev/null"
            git remote add ja git@github.com:${{ github.repository }}
            git remote add up https://github.com/voidzero-dev/vite-plus
            git fetch ja main
            git switch -t ja/main
          fi

      # --filter=blob:none をつける意味は現状あまり無い
      - run: |
          git fetch ja main sync/subtree sync/upstream
          git fetch up main
        # force-pushされた場合ここで落ちる
      - run: git push ja up/main:sync/upstream
      # syncを実体化しておく
      - run: |
          git switch sync/subtree
          git pull
          git switch sync/upstream
          git pull
        # これが結構遅い
      - run: git subtree split --prefix=docs -b sync/subtree
      - run: git push ja sync/subtree
      # 自動同期を試みる
      - run: |
          git switch main
          git pull
      # コンフリクトが起きたらここで落ちる
      - run: git merge sync/subtree
      - run: git push
