on:
  workflow_dispatch:
    inputs:
      push-args:
        type: string
        required: false
        description: 'git push args (e.g, -f)'
        default: ''
  schedule:
    - cron: '47 5 * * *'

concurrency:
  group: main

permissions:
  contents: write

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - run: git init
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - run: |
          git remote add ja https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}
          git remote add up https://github.com/voidzero-dev/vite-plus
        # --filter=blob:none をつける意味はあまり無い
      - run: |
          git fetch ja main sync/subtree sync/upstream
          git fetch up main
        # force-pushされた場合ここで落ちる
      - run: git push ${{ inputs.push-args }} ja up/main ja/sync/upstream
      - run: git remote remove up
        # syncを実体化しておく
      - run: git switch sync/subtree
      - run: git switch sync/upstream
        # これが結構遅い
      - run: git subtree split --prefix=docs -b sync/subtree
      - run: git push ${{ inputs.push-args }} ja sync/subtree
        # 自動同期を試みる
      - run: git switch main
        # コンフリクトが起きたらここで落ちる
      - run: git merge sync/subtree
      - run: git push
